export const Footer = () =>{
    return(
        
        <div>
              <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
        <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
      <div>sdsdsdsd</div>
    </div>
    );
}